// <auto-generated />
using System;
using CA.ClinicaIA.Infra.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CA.ClinicaIA.Infra.Data.Migrations
{
    [DbContext(typeof(ClinicaIAContext))]
    partial class ClinicaIAContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CA.ClinicaIA.Infra.Data.Tables.AgendamentoTable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClinicaId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("DataHora")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GoogleEventId")
                        .HasColumnType("text");

                    b.Property<int?>("GuiaId")
                        .HasColumnType("integer");

                    b.Property<int>("PacienteId")
                        .HasColumnType("integer");

                    b.Property<int>("ProcedimentoId")
                        .HasColumnType("integer");

                    b.Property<int>("ProfissionalId")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ClinicaId");

                    b.HasIndex("GuiaId");

                    b.HasIndex("PacienteId");

                    b.HasIndex("ProcedimentoId");

                    b.HasIndex("ProfissionalId");

                    b.ToTable("Agendamentos", (string)null);
                });

            modelBuilder.Entity("CA.ClinicaIA.Infra.Data.Tables.ClinicaTable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Configuracoes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Clinicas", (string)null);
                });

            modelBuilder.Entity("CA.ClinicaIA.Infra.Data.Tables.GuiaProcedimentoTable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("GuiaId")
                        .HasColumnType("integer");

                    b.Property<int?>("GuiaTableId")
                        .HasColumnType("integer");

                    b.Property<int>("ProcedimentoId")
                        .HasColumnType("integer");

                    b.Property<int>("QuantidadeAutorizada")
                        .HasColumnType("integer");

                    b.Property<int>("QuantidadeRealizada")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("GuiaId");

                    b.HasIndex("GuiaTableId");

                    b.HasIndex("ProcedimentoId");

                    b.ToTable("GuiasProcedimentos", (string)null);
                });

            modelBuilder.Entity("CA.ClinicaIA.Infra.Data.Tables.GuiaTable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClinicaId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PacienteId")
                        .HasColumnType("integer");

                    b.Property<int>("PlanoId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ClinicaId");

                    b.HasIndex("PacienteId");

                    b.HasIndex("PlanoId");

                    b.ToTable("Guias", (string)null);
                });

            modelBuilder.Entity("CA.ClinicaIA.Infra.Data.Tables.LancamentoFinanceiroTable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AgendamentoId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PacienteId")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Valor")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("AgendamentoId");

                    b.HasIndex("PacienteId");

                    b.ToTable("LancamentosFinanceiros", (string)null);
                });

            modelBuilder.Entity("CA.ClinicaIA.Infra.Data.Tables.PacienteTable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CarteirinhaConvenio")
                        .HasColumnType("text");

                    b.Property<int>("ClinicaId")
                        .HasColumnType("integer");

                    b.Property<string>("Cpf")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataNascimento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DocumentoResponsavel")
                        .HasColumnType("text");

                    b.Property<string>("EmailResponsavel")
                        .HasColumnType("text");

                    b.Property<string>("GoogleContactId")
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NomeResponsavel")
                        .HasColumnType("text");

                    b.Property<string>("TelefoneResponsavel")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ClinicaId");

                    b.ToTable("Pacientes", (string)null);
                });

            modelBuilder.Entity("CA.ClinicaIA.Infra.Data.Tables.PlanoTable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClinicaId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Intercambio")
                        .HasColumnType("boolean");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ClinicaId");

                    b.ToTable("Planos", (string)null);
                });

            modelBuilder.Entity("CA.ClinicaIA.Infra.Data.Tables.ProcedimentoPlanoTable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PlanoId")
                        .HasColumnType("integer");

                    b.Property<int>("ProcedimentoId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("ValorCoparticipacao")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ValorProcedimento")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("PlanoId");

                    b.HasIndex("ProcedimentoId");

                    b.ToTable("ProcedimentoPlanos", (string)null);
                });

            modelBuilder.Entity("CA.ClinicaIA.Infra.Data.Tables.ProcedimentoTable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClinicaId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ClinicaId");

                    b.ToTable("Procedimentos", (string)null);
                });

            modelBuilder.Entity("CA.ClinicaIA.Infra.Data.Tables.ProfissionalTable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClinicaId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GoogleAccountId")
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ClinicaId");

                    b.ToTable("Profissionais", (string)null);
                });

            modelBuilder.Entity("CA.ClinicaIA.Infra.Data.Tables.ProntuarioTable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AgendamentoId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TextoAudioOriginal")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TextoProcessado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AgendamentoId")
                        .IsUnique();

                    b.ToTable("Prontuarios", (string)null);
                });

            modelBuilder.Entity("CA.ClinicaIA.Infra.Data.Tables.AgendamentoTable", b =>
                {
                    b.HasOne("CA.ClinicaIA.Infra.Data.Tables.ClinicaTable", "Clinica")
                        .WithMany()
                        .HasForeignKey("ClinicaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CA.ClinicaIA.Infra.Data.Tables.GuiaTable", "Guia")
                        .WithMany()
                        .HasForeignKey("GuiaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CA.ClinicaIA.Infra.Data.Tables.PacienteTable", "Paciente")
                        .WithMany()
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CA.ClinicaIA.Infra.Data.Tables.ProcedimentoTable", "Procedimento")
                        .WithMany()
                        .HasForeignKey("ProcedimentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CA.ClinicaIA.Infra.Data.Tables.ProfissionalTable", "Profissional")
                        .WithMany()
                        .HasForeignKey("ProfissionalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Clinica");

                    b.Navigation("Guia");

                    b.Navigation("Paciente");

                    b.Navigation("Procedimento");

                    b.Navigation("Profissional");
                });

            modelBuilder.Entity("CA.ClinicaIA.Infra.Data.Tables.GuiaProcedimentoTable", b =>
                {
                    b.HasOne("CA.ClinicaIA.Infra.Data.Tables.GuiaTable", "Guia")
                        .WithMany()
                        .HasForeignKey("GuiaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CA.ClinicaIA.Infra.Data.Tables.GuiaTable", null)
                        .WithMany("Procedimentos")
                        .HasForeignKey("GuiaTableId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CA.ClinicaIA.Infra.Data.Tables.ProcedimentoTable", "Procedimento")
                        .WithMany()
                        .HasForeignKey("ProcedimentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Guia");

                    b.Navigation("Procedimento");
                });

            modelBuilder.Entity("CA.ClinicaIA.Infra.Data.Tables.GuiaTable", b =>
                {
                    b.HasOne("CA.ClinicaIA.Infra.Data.Tables.ClinicaTable", "Clinica")
                        .WithMany()
                        .HasForeignKey("ClinicaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CA.ClinicaIA.Infra.Data.Tables.PacienteTable", "Paciente")
                        .WithMany()
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CA.ClinicaIA.Infra.Data.Tables.PlanoTable", "Plano")
                        .WithMany()
                        .HasForeignKey("PlanoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Clinica");

                    b.Navigation("Paciente");

                    b.Navigation("Plano");
                });

            modelBuilder.Entity("CA.ClinicaIA.Infra.Data.Tables.LancamentoFinanceiroTable", b =>
                {
                    b.HasOne("CA.ClinicaIA.Infra.Data.Tables.AgendamentoTable", "Agendamento")
                        .WithMany("LancamentosFinanceiros")
                        .HasForeignKey("AgendamentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CA.ClinicaIA.Infra.Data.Tables.PacienteTable", "Paciente")
                        .WithMany()
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Agendamento");

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("CA.ClinicaIA.Infra.Data.Tables.PacienteTable", b =>
                {
                    b.HasOne("CA.ClinicaIA.Infra.Data.Tables.ClinicaTable", "Clinica")
                        .WithMany()
                        .HasForeignKey("ClinicaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Clinica");
                });

            modelBuilder.Entity("CA.ClinicaIA.Infra.Data.Tables.PlanoTable", b =>
                {
                    b.HasOne("CA.ClinicaIA.Infra.Data.Tables.ClinicaTable", "Clinica")
                        .WithMany()
                        .HasForeignKey("ClinicaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Clinica");
                });

            modelBuilder.Entity("CA.ClinicaIA.Infra.Data.Tables.ProcedimentoPlanoTable", b =>
                {
                    b.HasOne("CA.ClinicaIA.Infra.Data.Tables.PlanoTable", "Plano")
                        .WithMany()
                        .HasForeignKey("PlanoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CA.ClinicaIA.Infra.Data.Tables.ProcedimentoTable", "Procedimento")
                        .WithMany("ProcedimentoPlanos")
                        .HasForeignKey("ProcedimentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Plano");

                    b.Navigation("Procedimento");
                });

            modelBuilder.Entity("CA.ClinicaIA.Infra.Data.Tables.ProcedimentoTable", b =>
                {
                    b.HasOne("CA.ClinicaIA.Infra.Data.Tables.ClinicaTable", "Clinica")
                        .WithMany()
                        .HasForeignKey("ClinicaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Clinica");
                });

            modelBuilder.Entity("CA.ClinicaIA.Infra.Data.Tables.ProfissionalTable", b =>
                {
                    b.HasOne("CA.ClinicaIA.Infra.Data.Tables.ClinicaTable", "Clinica")
                        .WithMany()
                        .HasForeignKey("ClinicaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Clinica");
                });

            modelBuilder.Entity("CA.ClinicaIA.Infra.Data.Tables.ProntuarioTable", b =>
                {
                    b.HasOne("CA.ClinicaIA.Infra.Data.Tables.AgendamentoTable", "Agendamento")
                        .WithOne("Prontuario")
                        .HasForeignKey("CA.ClinicaIA.Infra.Data.Tables.ProntuarioTable", "AgendamentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Agendamento");
                });

            modelBuilder.Entity("CA.ClinicaIA.Infra.Data.Tables.AgendamentoTable", b =>
                {
                    b.Navigation("LancamentosFinanceiros");

                    b.Navigation("Prontuario")
                        .IsRequired();
                });

            modelBuilder.Entity("CA.ClinicaIA.Infra.Data.Tables.GuiaTable", b =>
                {
                    b.Navigation("Procedimentos");
                });

            modelBuilder.Entity("CA.ClinicaIA.Infra.Data.Tables.ProcedimentoTable", b =>
                {
                    b.Navigation("ProcedimentoPlanos");
                });
#pragma warning restore 612, 618
        }
    }
}
